services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
    container_name: promtior-backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/chroma_db:/app/chroma_db
    restart: unless-stopped
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
    container_name: promtior-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  ollama_data: {}
  chroma_data: {}
