site_name: ai-assistant | Documentation
site_description: ai-assistant Documentation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: black
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

plugins:
  - search

nav:
  - Project: index.md
  - Overview: overview.md
  - Architecture: architecture.md