site_name: Docs Chat AI Assistant
site_description: ai-assistant Documentation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: black
    accent: blue
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  icon: fontawesome/brands/github

repo_url: https://github.com/xlmriosx/promtior-ai-assistant
repo_name: GitHub 

plugins:
  - search

nav:
  - Introduction: index.md
  - Overview: overview.md
  - Architecture: architecture.md
  